version: '3.8'

services:
  # --- CONTENEDOR 1: ARHIOZ GYM API (FASTAPI) ---
  api:
    build: .                                  # Busca el dockerfile en la carpeta actual.
    image: arhioz_gym-api:1.0                  # Nombre y version que tendra la imagen generada.
    container_name: arhioz_gym-api-produccion  # Nombre del contenedor activo.
    ports:
      - "8000:8000"                           # Mapeo: Puerto de mi equipo -> Puerto del Contenedor
    env_file:
      - .env                                  # Inyecta las variables del archivo .env local.
    depends_on:
      - db                                    # Espera a que el contenedor "db" encienda primero.
    environment:
       - DATABASE_URL=postgresql+asyncpg://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    restart: always

  # --- CONTENEDOR 2: BASE DE DATOS (POSTGRESQL) ---
  db:
    image: postgres:16-alpine                 # Descarga la version optimizada y ligera de Postgres 16
    container_name: arhioz_gym-db-produccion   # Nombre del contenedor activo.
    environment:
      POSTGRES_USER: ${DB_USER}               # Al usar ${DB_USER} utiliza los datos que se encuentran en el archivo .env, siempre y cuando este en el mismo directorio donde se ejecuta el docker compose up -d
      POSTGRES_PASSWORD: ${DB_PASSWORD}       # Docker Compose busca estos datos automaticamente en el archivo .env sin necesidad de importar nada.
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data_produccion:/var/lib/postgresql/data
    restart: always

# --- DEFINICIÓN DE VOLÚMENES GLOBALES ---
volumes:
  postgres_data_produccion: