"""crear tablas iniciales

Revision ID: 1f459623c49c
Revises: 
Create Date: 2026-08-17 11:03:15.951872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f459623c49c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('enfermedades', sa.String(), nullable=True),
    sa.Column('contacto_emergencia', sa.String(length=80), nullable=True),
    sa.Column('telefono_emergencia', sa.String(length=20), nullable=True),
    sa.Column('huella_hash', sa.String(), nullable=False),
    sa.Column('fecha_inscripcion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_contacto_emergencia'), 'clientes', ['contacto_emergencia'], unique=False)
    op.create_index(op.f('ix_clientes_email'), 'clientes', ['email'], unique=True)
    op.create_index(op.f('ix_clientes_huella_hash'), 'clientes', ['huella_hash'], unique=True)
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_index(op.f('ix_clientes_nombre'), 'clientes', ['nombre'], unique=True)
    op.create_index(op.f('ix_clientes_telefono'), 'clientes', ['telefono'], unique=True)
    op.create_index(op.f('ix_clientes_telefono_emergencia'), 'clientes', ['telefono_emergencia'], unique=False)
    op.create_table('planes_membresia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_membresia', sa.Enum('DIA', 'SEMANA', 'MENSUAL', 'TRIMESTRAL', 'SEMESTRAL', 'ANUAL', 'OTRO', name='tipomembresia_enum'), nullable=True),
    sa.Column('duracion_dias', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planes_membresia_id'), 'planes_membresia', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_nombre'), 'roles', ['nombre'], unique=True)
    op.create_table('personal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('turno', sa.Enum('MATUTINO', 'VESPERTINO', 'NOCTURNO', name='tipoturno_enum'), nullable=True),
    sa.Column('horas_asignadas', sa.Integer(), nullable=False),
    sa.Column('huella_hash', sa.String(), nullable=False),
    sa.Column('fecha_de_alta', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_email'), 'personal', ['email'], unique=True)
    op.create_index(op.f('ix_personal_huella_hash'), 'personal', ['huella_hash'], unique=True)
    op.create_index(op.f('ix_personal_id'), 'personal', ['id'], unique=False)
    op.create_index(op.f('ix_personal_nombre'), 'personal', ['nombre'], unique=True)
    op.create_index(op.f('ix_personal_rol_id'), 'personal', ['rol_id'], unique=False)
    op.create_index(op.f('ix_personal_telefono'), 'personal', ['telefono'], unique=True)
    op.create_table('suscripciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('plan_membresia_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('monto_pagado', sa.Float(), nullable=False),
    sa.Column('estado', sa.Enum('ACTIVA', 'VENCIDA', 'CANCELADA', 'CONGELADA', 'OTRO', name='estadosuscripcion_enum'), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_membresia_id'], ['planes_membresia.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suscripciones_cliente_id'), 'suscripciones', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_suscripciones_id'), 'suscripciones', ['id'], unique=False)
    op.create_index(op.f('ix_suscripciones_plan_membresia_id'), 'suscripciones', ['plan_membresia_id'], unique=False)
    op.create_table('asistencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_usuario', sa.Enum('CLIENTE', 'PERSONAL', 'OTRO', name='tipousuario_enum'), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('personal_id', sa.Integer(), nullable=True),
    sa.Column('tipo_evento', sa.Enum('ENTRADA', 'SALIDA', name='tipoevento_enum'), nullable=True),
    sa.Column('fecha_evento', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(cliente_id IS NOT NULL AND personal_id IS NULL) OR (cliente_id IS NULL AND personal_id IS NOT NULL)', name='check_asistencia_usuario_exclusivo'),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['personal_id'], ['personal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asistencias_cliente_id'), 'asistencias', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_asistencias_id'), 'asistencias', ['id'], unique=False)
    op.create_index(op.f('ix_asistencias_personal_id'), 'asistencias', ['personal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asistencias_personal_id'), table_name='asistencias')
    op.drop_index(op.f('ix_asistencias_id'), table_name='asistencias')
    op.drop_index(op.f('ix_asistencias_cliente_id'), table_name='asistencias')
    op.drop_table('asistencias')
    op.drop_index(op.f('ix_suscripciones_plan_membresia_id'), table_name='suscripciones')
    op.drop_index(op.f('ix_suscripciones_id'), table_name='suscripciones')
    op.drop_index(op.f('ix_suscripciones_cliente_id'), table_name='suscripciones')
    op.drop_table('suscripciones')
    op.drop_index(op.f('ix_personal_telefono'), table_name='personal')
    op.drop_index(op.f('ix_personal_rol_id'), table_name='personal')
    op.drop_index(op.f('ix_personal_nombre'), table_name='personal')
    op.drop_index(op.f('ix_personal_id'), table_name='personal')
    op.drop_index(op.f('ix_personal_huella_hash'), table_name='personal')
    op.drop_index(op.f('ix_personal_email'), table_name='personal')
    op.drop_table('personal')
    op.drop_index(op.f('ix_roles_nombre'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_planes_membresia_id'), table_name='planes_membresia')
    op.drop_table('planes_membresia')
    op.drop_index(op.f('ix_clientes_telefono_emergencia'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_telefono'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_nombre'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_huella_hash'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_email'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_contacto_emergencia'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
