"""agregar tabla de pagos

Revision ID: 7c2a5be5d92c
Revises: b1a1b8933901
Create Date: 2026-09-07 21:59:29.153617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c2a5be5d92c'
down_revision: Union[str, Sequence[str], None] = 'b1a1b8933901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folio', sa.String(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('metodo_pago', sa.Enum('EFECTIVO', 'TARJETA_CREDITO', 'TARJETA_DEBITO', 'TRANSFERENCIA', 'OTRO', name='metodopago'), nullable=False),
    sa.Column('concepto', sa.String(), nullable=True),
    sa.Column('fecha_pago', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('suscripcion_id', sa.Integer(), nullable=True),
    sa.Column('personal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['personal_id'], ['personal.id'], ),
    sa.ForeignKeyConstraint(['suscripcion_id'], ['suscripciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagos_folio'), 'pagos', ['folio'], unique=True)
    op.create_index(op.f('ix_pagos_id'), 'pagos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pagos_id'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_folio'), table_name='pagos')
    op.drop_table('pagos')
    # ### end Alembic commands ###
