"""agregar rol_id a clientes

Revision ID: b1a1b8933901
Revises: e230995becac
Create Date: 2026-08-25 17:45:12.085037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1a1b8933901'
down_revision: Union[str, Sequence[str], None] = 'e230995becac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('rol_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'clientes', 'roles', ['rol_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clientes', type_='foreignkey')
    op.drop_column('clientes', 'rol_id')
    # ### end Alembic commands ###
