"""actualizar fecha_de_alta en clientes

Revision ID: e230995becac
Revises: 1f459623c49c
Create Date: 2026-08-20 13:00:45.236931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e230995becac'
down_revision: Union[str, Sequence[str], None] = '1f459623c49c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asistencias', 'tipo_usuario',
               existing_type=postgresql.ENUM('CLIENTE', 'PERSONAL', 'OTRO', name='tipousuario_enum'),
               nullable=False)
    op.add_column('clientes', sa.Column('fecha_de_alta', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_clientes_nombre'), table_name='clientes')
    op.create_index(op.f('ix_clientes_nombre'), 'clientes', ['nombre'], unique=False)
    op.drop_column('clientes', 'fecha_inscripcion')
    op.add_column('personal', sa.Column('password', sa.String(), nullable=True))
    op.alter_column('personal', 'turno',
               existing_type=postgresql.ENUM('MATUTINO', 'VESPERTINO', 'NOCTURNO', name='tipoturno_enum'),
               nullable=False)
    op.drop_index(op.f('ix_personal_nombre'), table_name='personal')
    op.create_index(op.f('ix_personal_nombre'), 'personal', ['nombre'], unique=False)
    op.create_index(op.f('ix_personal_password'), 'personal', ['password'], unique=False)
    op.alter_column('planes_membresia', 'tipo_membresia',
               existing_type=postgresql.ENUM('DIA', 'SEMANA', 'MENSUAL', 'TRIMESTRAL', 'SEMESTRAL', 'ANUAL', 'OTRO', name='tipomembresia_enum'),
               nullable=False)
    op.alter_column('suscripciones', 'estado',
               existing_type=postgresql.ENUM('ACTIVA', 'VENCIDA', 'CANCELADA', 'CONGELADA', 'OTRO', name='estadosuscripcion_enum'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('suscripciones', 'estado',
               existing_type=postgresql.ENUM('ACTIVA', 'VENCIDA', 'CANCELADA', 'CONGELADA', 'OTRO', name='estadosuscripcion_enum'),
               nullable=True)
    op.alter_column('planes_membresia', 'tipo_membresia',
               existing_type=postgresql.ENUM('DIA', 'SEMANA', 'MENSUAL', 'TRIMESTRAL', 'SEMESTRAL', 'ANUAL', 'OTRO', name='tipomembresia_enum'),
               nullable=True)
    op.drop_index(op.f('ix_personal_password'), table_name='personal')
    op.drop_index(op.f('ix_personal_nombre'), table_name='personal')
    op.create_index(op.f('ix_personal_nombre'), 'personal', ['nombre'], unique=True)
    op.alter_column('personal', 'turno',
               existing_type=postgresql.ENUM('MATUTINO', 'VESPERTINO', 'NOCTURNO', name='tipoturno_enum'),
               nullable=True)
    op.drop_column('personal', 'password')
    op.add_column('clientes', sa.Column('fecha_inscripcion', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_clientes_nombre'), table_name='clientes')
    op.create_index(op.f('ix_clientes_nombre'), 'clientes', ['nombre'], unique=True)
    op.drop_column('clientes', 'fecha_de_alta')
    op.alter_column('asistencias', 'tipo_usuario',
               existing_type=postgresql.ENUM('CLIENTE', 'PERSONAL', 'OTRO', name='tipousuario_enum'),
               nullable=True)
    # ### end Alembic commands ###
